baseurl = "http://talk.coffee/"
languageCode = "en-us"
title = "Talk Coffee"
paginate = 10
paginatePath = "page"

[params]
  author = "E John Feig"
  description = "A landing page for the Slack Talk Coffee community"
